version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: videoprocessing/latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:8080'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail          
    ngrok:
        image: ngrok/ngrok
        environment:
            - NGROK_AUTHTOKEN=1VoZIAhKFSjWh1aCwj2D6feZuF5_2D8AYPRTRTyDnhjc3SV6u
        command: ngrok http 8080
        networks:
            - sail
        depends_on:
            - app
networks:
    sail:
        driver: bridge
